### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/colourpycker#15]
Congrats on finishing Milestone 1! We can see that you put some thought into this project. Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

Group 17

- [ ] There are useless titles for this milestone submission (ex. Usage) -2

- [x] Missing Function 2. Not all the team members have been assigned to an issue - mechanics -2

- [x] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing, for example, I’m not sure what output extcolors gives?) -2

All and all I think this group did a great job of creating issues to make sure everyone was assigned a function. The project structure was done well. Each function’s docstrings were also done well. Lastly, the branches were also done well in terms of naming them useful names, as well as not having redundant branches. As a side note remember to have every member commit in the GitHub repo equally.

**Comment by shaunhutch** [comment]
Hello @andytai7, thanks for your feedback. We have a couple of questions about the specific feedback for understanding since we need to address these concerns in the future. 

1. The Usage title was left in as we have not made the functions yet. We were going to add the usage once the functions were written. Were we supposed to get rid of it?
2. The function 2 issue was created and assigned to @ataciuk. It was also assigned to Milestone 1 and was on the project board, but it was not closed. Maybe that is why you thought it was missing?
3. `extcolors` is a package that we were importing for our project. I don't think we need to write documentation for that? 

Thank you!

**Comment by andytai7** [comment]
1. Yes, there should only be items on the github repo that is needed for that milestone. Anything extra is not necssary. 


2. Function 2's issue was created 17 minutes ago. 

<img width="549" alt="Screenshot 2023-01-17 at 3 16 23 PM" src="https://user-images.githubusercontent.com/45893111/213033197-8573c7b2-1683-4acf-bf2f-cda918469d10.png">

3. Oh i see, you are correct for this, marks changed +2

**Comment by shaunhutch** [comment]
1. Okay noted, we will ensure to follow this in future.
2. The screenshot shows that it was closed 17 minutes ago, and not created. If you open the issue it was created 4 days ago.
3. Thanks!

**Comment by andytai7** [comment]
2. Function issues for that milestone should be closed before milestone submission. Does that make sense?

**Comment by shaunhutch** [comment]
Got it, thanks

**Comment by andytai7** [comment]
Thank you and good luck on Milestone 2.
